# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keep',
            name='keep_counter',
        ),
        migrations.RemoveField(
            model_name='remove',
            name='remove_counter',
        ),
    ]
