# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_limit',
            field=models.DateTimeField(),
        ),
    ]
