# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20151217_0830'),
        ('random_board', '0002_auto_20151214_0613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='keep_cnt',
        ),
        migrations.RemoveField(
            model_name='post',
            name='remove_cnt',
        ),
        migrations.RemoveField(
            model_name='post',
            name='time_limit',
        ),
        migrations.AddField(
            model_name='post',
            name='keep',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='profiles.Keep'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='remove',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='profiles.Remove'),
            preserve_default=False,
        ),
    ]
