# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('random_board', '0003_auto_20151217_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='keep',
        ),
        migrations.RemoveField(
            model_name='post',
            name='remove',
        ),
    ]
